version: '0.0.1'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=gaston
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://gaston:postgres@database:5432/my_db
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/src/app
      - /src/app/node_modules
      

